AllCops:
  UseCache: true
  CacheRootDirectory: tmp/rubocop_cache
  MaxFilesInCache: 2000
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'tmp/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'ci/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150
  IgnoredPatterns: ['\A#']

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Style/ClassVars:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - 'describe'
    - 'context'
    - 'permissions'

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false
